Add docfx website for documentation
bonsai-rx/sgen pull request #51
Opened 2024-12-31 21:20 UTC by banchan86

This PR sets up the docfx infrastructure for documentation. Two points:
 
- The GitHub actions workflow `dotnet.yml` might need to be modified since source code has been moved.
- There is no GitHub Actions recipe added yet for online docs generation as it seems we are revamping the GitHub Actions workflow https://github.com/bonsai-rx/zeromq/pull/23 and I still need to learn how to do that.

2024-12-31 21:32 UTC, banchan86 commented
@bruno-f-cruz @glopesdev

2024-12-31 21:58 UTC, bruno-f-cruz requested changes
Let's remove the TOC references to the non existing articles for a cleaner PR history.

Also, can we leave the packages at the top level without moving them to a src folder? This is the current standard that I am using and also the what the bonsai core uses. Unless there has been a decision to use a different standard that I am not aware about.

2025-01-03 22:06 UTC, banchan86 commented
> Let's remove the TOC references to the non existing articles for a cleaner PR history.
> 
> Also, can we leave the packages at the top level without moving them to a src folder? This is the current standard that I am using and also the what the bonsai core uses. Unless there has been a decision to use a different standard that I am not aware about.

I have removed the TOC references to the non-existing articles. 

The Bonsai.Core probably isn't the best repo to emulate as it is structured quite differently from the other package repos (the `docs` is separated from the `src`), but the Bonsai.Core docs repo actually imports Bonsai.Core as a submodule under the `src` folder. The most recent Bonsai packages (Bonsai.Mixer, Bonsai.ML, Bonsai.PulsePal, etc) use this layout as well. But I have no strong feelings about it and the last commit moves the `src` back to the top level, @glopesdev can review and make the final decision.

2025-01-07 15:55 UTC, glopesdev reviewed
Looks good, only very minor comments, and one thing I was starting to investigate is whether to add the favicon and logo directly to the template in `docfx-tools` or not.

It won't be used for all projects, but it could be set as the default in case no icon is specified, similar to how the DocFX logo itself is part of the default template and used if no other asset is defined.

2025-01-08 01:41 UTC, glopesdev approved these changes

2025-01-08 01:55 UTC, glopesdev commented
@banchan86 looks good, maybe let's wait for the review and merge of https://github.com/bonsai-rx/zeromq/pull/23 and we can review whether we want to bring over some of the patterns used there.

2025-01-24 04:39 UTC, banchan86 commented
@glopesdev I reviewed the changes over at https://github.com/bonsai-rx/zeromq/pull/23 and adopted them here, if you want to take a look. I didn't bring over `global.json` as it conflicted with the .NET SDK version needed for unit testing in `dotnet.yml` and wasn't sure how to resolve it.

2025-03-09 02:33 UTC, bruno-f-cruz commented
@banchan86 @glopesdev any updates on this?

2025-03-13 14:52 UTC, glopesdev commented
> But I have no strong feelings about it and the last commit moves the src back to the top level, @glopesdev can review and make the final decision.

@banchan86 I'm happy moving the code into the `src` folder. I will try to do a bit of cherry picking of what you did since main had quite a few PRs merged since.

2025-03-14 17:20 UTC, glopesdev commented
@banchan86 As this project is more of a pure .NET tool project I ended up removing and simplifying a lot of details from both the DocFX template and the CI workflows and preparing https://github.com/bonsai-rx/sgen/pull/56 which will likely supersede this one.

I won't close it yet until I have add time to test it and integrate with the contents at #50.

2025-03-16 20:46 UTC, closed without merging